import {
  Tenant,
  User,
  Customer,
  Product,
  InstallmentPlan,
  WalletAccount,
  HandoverRequest,
  ExpenseRecord,
  ArticlePost,
} from "./types";
import { ChainedLedgerBlock, computeBlockHash } from "../crypto/hash-chain";

export const initialTenants: Tenant[] = [
  {
    id: "tenant_chiniot",
    name: "Rajpoot Traders - Chiniot Main Head Office",
    code: "CHN-MAIN",
    brandHeader: "راجپوت ٹریڈرز (رجسٹرڈ) - محلہ رحمن آباد چنیوٹ",
    urduBrandName: "راجپوت ٹریڈرز (رجسٹرڈ) — محلہ رحمن آباد چنیوٹ",
    address: "محلہ رحمن آباد، چنیوٹ، پنجاب، پاکستان",
    contact: "0311-4813850",
    status: "ACTIVE",
    ownerName: "Usama Rajpoot",
    ownerEmail: "musama4288921@gmail.com",
    licenseValidUntil: "2030-12-31",
    createdAt: "2024-01-01T00:00:00Z",
  },
];

export const initialUsers: User[] = [
  {
    id: "usr_super_admin",
    tenantId: "tenant_chiniot",
    name: "Usama Rajpoot",
    email: "musama4288921@gmail.com",
    password: "33admin401",
    role: "SUPER_ADMIN",
    phone: "0311-4813850",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150",
    status: "ACTIVE",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "usr_owner_chn",
    tenantId: "tenant_chiniot",
    name: "حاجی محمد راجپوت (Haji Muhammad Rajpoot)",
    email: "owner@rajpoottraders.com",
    password: "owner123",
    role: "OWNER",
    phone: "0311-4813850",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
    status: "ACTIVE",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "usr_salesman_zaheem",
    tenantId: "tenant_chiniot",
    name: "ضہیم سیلز مین (Zaheem Salesman)",
    email: "salesman@rajpoottraders.com",
    password: "sales123",
    role: "BRANCH_MANAGER",
    phone: "0300-7654321",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150",
    status: "ACTIVE",
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "usr_recovery_bilal",
    tenantId: "tenant_chiniot",
    name: "بلال احمد (Bilal Recovery Officer)",
    email: "recovery@rajpoottraders.com",
    password: "recovery123",
    role: "FIELD_RECOVERY",
    phone: "0321-9876543",
    assignedRouteZone: "محلہ رحمن آباد و مسلم بازار چنیوٹ",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150",
    status: "ACTIVE",
    createdAt: "2024-01-01T00:00:00Z",
  },
];

export const initialCustomers: Customer[] = [
  {
    id: "cust_khata_6",
    tenantId: "tenant_chiniot",
    fullName: "اکبر علی (Akbar Ali)",
    fatherName: "نصرت حسین (Nusrat Hussain)",
    cnic: "33202-6717585-1",
    phone: "0333-6717585",
    address: "نصرت کشیدہ کاری، نزد دیسی مسجد، چنیوٹ",
    landmark: "دیسی مسجد چنیوٹ",
    city: "چنیوٹ (Chiniot)",
    zoneArea: "محلہ رحمن آباد و مسلم بازار چنیوٹ",
    guarantors: [
      {
        id: "g_1_akbar",
        fullName: "محمد اسلم (ضامن 1)",
        fatherName: "عبدالرشید",
        cnic: "33202-1234567-1",
        phone: "0300-1122334",
        relation: "پڑوسی و کشیدہ کار",
        address: "نزد دیسی مسجد چنیوٹ",
        workplace: "مارکیٹ",
        landmark: "دیسی مسجد",
      },
    ],
    riskScore: 10,
    isDefaulter: false,
    createdAt: "2026-08-03T00:00:00Z",
  },
];

export const initialPlans: InstallmentPlan[] = [
  {
    id: "plan_khata_6",
    planNumber: "RT-CHN-000006",
    khataNumber: "6",
    tenantId: "tenant_chiniot",
    customerId: "cust_khata_6",
    customerName: "اکبر علی ولد نصرت حسین",
    customerCnic: "33202-6717585-1",
    customerPhone: "0333-6717585",
    salesmanName: "ضہیم (Zaheem)",
    salesmanId: "usr_salesman_zaheem",
    productId: "prod_istari_heavy",
    productTitle: "استری (Heavy Weight Electric Iron)",
    imeiSerial: "SN-IST-0006",
    cashPrice: 5800,
    downPayment: 500,
    markupRatePct: 17,
    totalMarkup: 1000,
    totalFinanced: 6800,
    durationMonths: 13,
    totalInstallmentsCount: 13,
    installmentFrequency: "WEEKLY",
    collectionIntervalDays: 7,
    collectionDayName: "ہفتہ (Saturday)",
    monthlyInstallment: 500,
    accumulatedShortArrears: 0,
    status: "ACTIVE",
    startDate: "2026-08-03T00:00:00Z",
    endDate: "2026-11-03T00:00:00Z",
    areaZone: "محلہ رحمن آباد و مسلم بازار چنیوٹ",
    contractVerified: true,
    tamperProofHash: "HASH_CHN_KHATA_6",
    guarantorIds: ["g_1_akbar"],
    schedule: [
      { installmentNo: 1, dueDate: "2026-08-08", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 500, paidDate: "2026-08-08", status: "PAID", collectedBy: "ضہیم / بلال", notes: "Akbar sign" },
      { installmentNo: 2, dueDate: "2026-08-16", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 500, paidDate: "2026-08-16", status: "PAID", collectedBy: "ضہیم / بلال" },
      { installmentNo: 3, dueDate: "2026-08-22", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 1500, paidDate: "2026-08-22", status: "PAID", collectedBy: "ضہیم / بلال", notes: "Lump sum advance 3 weeks" },
      { installmentNo: 4, dueDate: "2026-08-22", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 500, paidDate: "2026-08-22", status: "PAID", collectedBy: "ضہیم / بلال" },
      { installmentNo: 5, dueDate: "2026-08-29", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 1000, paidDate: "2026-08-29", status: "PAID", collectedBy: "ضہیم / بلال" },
      { installmentNo: 6, dueDate: "2026-09-05", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 7, dueDate: "2026-09-12", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 8, dueDate: "2026-09-19", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 9, dueDate: "2026-09-26", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 10, dueDate: "2026-10-03", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 11, dueDate: "2026-10-10", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 12, dueDate: "2026-10-17", principalDue: 500, lateFee: 0, shortArrears: 0, totalDue: 500, amountPaid: 0, status: "PENDING" },
      { installmentNo: 13, dueDate: "2026-10-24", principalDue: 300, lateFee: 0, shortArrears: 0, totalDue: 300, amountPaid: 0, status: "PENDING" },
    ],
  },
];

export const initialHandovers: HandoverRequest[] = [];
export const initialExpenses: ExpenseRecord[] = [];

export const initialProducts: Product[] = [
  {
    id: "prod_istari_heavy",
    tenantId: "tenant_chiniot",
    title: "استری (Heavy Weight National / Haier Electric Iron)",
    brand: "National / Haier",
    category: "ELECTRIC_IRONS",
    cashPrice: 5800,
    installmentPrice: 6800,
    defaultDownPayment: 500,
    defaultInstallmentAmount: 500,
    defaultFrequency: "WEEKLY",
    defaultTotalInstallments: 13,
    minDownPaymentPct: 10,
    maxTenureMonths: 6,
    imeiSerialList: ["SN-IST-0001", "SN-IST-0002", "SN-IST-0003"],
    specs: { "قسم": "Heavy Weight Iron", "وارنٹی": "1 سال", "پاور": "1000W" },
    inStock: true,
    stockQuantity: 25,
    image: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=600",
  },
  {
    id: "prod_ceiling_fan",
    tenantId: "tenant_chiniot",
    title: "سیلنگ فین (GFC / Royal 56 Inch Deluxe Ceiling Fan)",
    brand: "GFC / Royal",
    category: "FANS",
    cashPrice: 8500,
    installmentPrice: 10500,
    defaultDownPayment: 1000,
    defaultInstallmentAmount: 500,
    defaultFrequency: "WEEKLY",
    defaultTotalInstallments: 19,
    minDownPaymentPct: 10,
    maxTenureMonths: 6,
    imeiSerialList: ["SN-FAN-881", "SN-FAN-882"],
    specs: { "سائز": "56 Inch", "وائنڈنگ": "99.9% خالص تانبا (Pure Copper)", "وارنٹی": "2 سال" },
    inStock: true,
    stockQuantity: 18,
    image: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600",
  },
  {
    id: "prod_washing_machine",
    tenantId: "tenant_chiniot",
    title: "سپر ایشیا واشنگ مشین (Super Asia 10kg Washing Machine)",
    brand: "Super Asia",
    category: "HOME_APPLIANCES",
    cashPrice: 28000,
    installmentPrice: 34000,
    defaultDownPayment: 4000,
    defaultInstallmentAmount: 2500,
    defaultFrequency: "MONTHLY",
    defaultTotalInstallments: 12,
    minDownPaymentPct: 15,
    maxTenureMonths: 12,
    imeiSerialList: ["SA-WM-1009"],
    specs: { "گنجائش": "10 KG", "موٹر": "کاپر موٹر", "وارنٹی": "5 سال موٹر وارنٹی" },
    inStock: true,
    stockQuantity: 10,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=600",
  },
  {
    id: "prod_haier_18hfp",
    tenantId: "tenant_chiniot",
    title: "ہائیر 1.5 ٹن انورٹر اے سی (Haier 1.5 Ton Inverter AC)",
    brand: "Haier",
    category: "AIR_CONDITIONERS",
    cashPrice: 165000,
    installmentPrice: 195000,
    defaultDownPayment: 30000,
    defaultInstallmentAmount: 13750,
    defaultFrequency: "MONTHLY",
    defaultTotalInstallments: 12,
    minDownPaymentPct: 15,
    maxTenureMonths: 18,
    imeiSerialList: ["HR-AC-2026-9011"],
    specs: { "صلاحیت": "1.5 Ton T3 Inverter", "بجلی بچت": "65% انرجی سیونگ", "وارنٹی": "10 سال کمپریسر" },
    inStock: true,
    stockQuantity: 8,
    image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600",
  },
  {
    id: "prod_honda_cd70",
    tenantId: "tenant_chiniot",
    title: "ہونڈا CD70 موٹر سائیکل (Honda CD 70cc 2026 Model)",
    brand: "Atlas Honda",
    category: "MOTORBIKES",
    cashPrice: 168500,
    installmentPrice: 198000,
    defaultDownPayment: 35000,
    defaultInstallmentAmount: 13580,
    defaultFrequency: "MONTHLY",
    defaultTotalInstallments: 12,
    minDownPaymentPct: 20,
    maxTenureMonths: 12,
    imeiSerialList: ["HND-ENG-988201"],
    specs: { "انجن": "4-Stroke OHC", "ایوریج": "65 km/l", "رجسٹریشن": "پنجاب" },
    inStock: true,
    stockQuantity: 12,
    image: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600",
  },
];

export const initialWallets: WalletAccount[] = [
  {
    id: "wall_owner_chn",
    tenantId: "tenant_chiniot",
    type: "OWNER_POCKET",
    name: "Owner Physical Cash (حاجی محمد راجپوت جیب)",
    balance: 0,
    updatedAt: "2026-08-31T00:00:00Z",
  },
  {
    id: "wall_counter_chn",
    tenantId: "tenant_chiniot",
    type: "COUNTER_TILL",
    name: "Chiniot Showroom Counter Till (کاؤنٹر دراز)",
    balance: 0,
    updatedAt: "2026-08-31T00:00:00Z",
  },
  {
    id: "wall_field_bilal",
    tenantId: "tenant_chiniot",
    type: "FIELD_IN_TRANSIT",
    name: "Field In-Transit (بلال احمد بیگ)",
    balance: 0,
    officerId: "usr_recovery_bilal",
    updatedAt: "2026-08-31T00:00:00Z",
  },
  {
    id: "wall_bank_mcb",
    tenantId: "tenant_chiniot",
    type: "DIGITAL_BANK",
    name: "Meezan Bank - Chiniot Katchery Branch",
    accountNumber: "02010108920192",
    bankName: "Meezan Bank Chiniot",
    balance: 0,
    updatedAt: "2026-08-31T00:00:00Z",
  },
];

export const initialLedgerChain: ChainedLedgerBlock[] = [
  {
    index: 0,
    id: "genesis_block",
    timestamp: "2024-01-01T00:00:00Z",
    payload: {
      id: "genesis_tx",
      tenantId: "tenant_chiniot",
      timestamp: "2024-01-01T00:00:00Z",
      type: "INTERNAL_TRANSFER",
      amount: 0,
      actorId: "system",
      notes: "RAJPOOT TRADERS CHINIOT - Blockchain Ledger Initialized",
    },
    prevHash: "0000000000000000000000000000000000000000000000000000000000000000",
    hash: "000000000019a8bc43f1190d79d19a2e379b38ecbc9102c91a74e792e3a61f91",
    signature: "SIG_GENESIS_CHAIN",
  },
];

export const initialArticles: ArticlePost[] = [
  {
    id: "art_1",
    slug: "chiniot-easy-installments-electronics-iron",
    title: "Easy Installments in Chiniot: Electric Irons, Fans & Appliances Guide",
    urduTitle: "چنیوٹ میں آسان ہفتہ وار اور ماہانہ اقساط پر الیکٹرانکس اور استری کا طریقہ کار",
    excerpt: "راجپوت ٹریڈرز چنیوٹ کے محلہ رحمن آباد میں آسان اقساط، نقد و قسط قیمت، اور شفاف معاہدے کی مکمل تفصیل۔",
    category: "اقساط گائیڈ",
    readTime: "3 min read",
    date: "2026-09-01",
    author: "Usama Rajpoot",
    contentHtml: "<p>راجپوت ٹریڈرز چنیوٹ میں گھریلو استعمال کی اشیاء جیسے استری، پنکھے، واشنگ مشین، اور انورٹر اے سی آسان ہفتہ وار (500 ہفتہ) اور ماہانہ اقساط پر فراہم کرتا ہے۔</p>",
    keywords: ["Rajpoot Traders Chiniot", "easy installments chiniot", "chiniot electronics qist"],
  },
];